services:
  <<PLUGIN_SERVER_SERVICE>>:
    image: <<PLUGIN_SERVER_IMAGE>>
    pull_policy: if_not_present
    container_name: <<PLUGIN_SERVER_DOCKER>>
    ports:
      - "<<PLUGIN_SERVER_HOST_PORT>>:<<PLUGIN_SERVER_PORT>>"
    environment:
      - HTTP_PROXY
      - HTTPS_PROXY
      - http_proxy
      - https_proxy
      - <<no_proxy_str>>
      - <<NO_PROXY_STR>>
    networks:
      - <<JIUWEN_NETWORK_NAME>>
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:<<PLUGIN_SERVER_PORT>>/system/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  <<JIUWEN_NETWORK_NAME>>:
    driver: bridge
