"""feat: add_obs_name_column

Revision ID: c84ee4a8efca
Revises: 7c2f1c9e3b1a
Create Date: 2026-03-02 13:50:47.247812

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from openjiuwen_studio.core.database.migration_utils import (
    table_exists,
    column_exists,
    index_exists,
)

# revision identifiers, used by Alembic.
revision: str = "c84ee4a8efca"
down_revision: Union[str, Sequence[str], None] = "7c2f1c9e3b1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("knowledge_base", schema=None) as batch_op:
        batch_op.drop_column("obs_name")

    with op.batch_alter_table("knowledge_base_document", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "obs_name",
                sa.String(length=1000),
                nullable=False,
                comment="OBS 存储路径在存储桶中",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("knowledge_base_document", schema=None) as batch_op:
        batch_op.drop_column("obs_name")

    with op.batch_alter_table("knowledge_base", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("obs_name", sa.VARCHAR(length=1000), nullable=True)
        )

    # ### end Alembic commands ###
