"""feat: add_obs_name_column

Revision ID: 83fa6b26d113
Revises: 9d63c16521a8
Create Date: 2026-03-02 13:34:28.117161

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from openjiuwen_studio.core.database.migration_utils import (
    table_exists,
    column_exists,
    index_exists,
)
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "83fa6b26d113"
down_revision: Union[str, Sequence[str], None] = "9d63c16521a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prompt_debug_context", schema=None) as batch_op:
        batch_op.drop_index("ix_prompt_debug_context_prompt_id")

    op.drop_table("prompt_debug_context")
    with op.batch_alter_table("prompt_debug_log", schema=None) as batch_op:
        batch_op.drop_index("ix_prompt_debug_log_debug_id")
        batch_op.drop_index("ix_prompt_debug_log_prompt_id")

    op.drop_table("prompt_debug_log")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_debug_log",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("prompt_id", sa.BIGINT(), nullable=False),
        sa.Column("space_id", sa.BIGINT(), nullable=False),
        sa.Column("prompt_key", sa.VARCHAR(length=128), nullable=False),
        sa.Column("version", sa.VARCHAR(length=128), nullable=False),
        sa.Column("input_tokens", sa.BIGINT(), nullable=True),
        sa.Column("output_tokens", sa.BIGINT(), nullable=True),
        sa.Column("started_at", sa.BIGINT(), nullable=True),
        sa.Column("ended_at", sa.BIGINT(), nullable=True),
        sa.Column("cost_ms", sa.BIGINT(), nullable=True),
        sa.Column("status_code", sa.INTEGER(), nullable=True),
        sa.Column("debugged_by", sa.VARCHAR(length=128), nullable=True),
        sa.Column("debug_id", sa.BIGINT(), nullable=False),
        sa.Column("debug_step", sa.INTEGER(), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.BIGINT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("prompt_debug_log", schema=None) as batch_op:
        batch_op.create_index(
            "ix_prompt_debug_log_prompt_id", ["prompt_id"], unique=False
        )
        batch_op.create_index(
            "ix_prompt_debug_log_debug_id", ["debug_id"], unique=False
        )

    op.create_table(
        "prompt_debug_context",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("prompt_id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("mock_contexts", sqlite.JSON(), nullable=True),
        sa.Column("mock_variables", sqlite.JSON(), nullable=True),
        sa.Column("mock_tools", sqlite.JSON(), nullable=True),
        sa.Column("debug_config", sqlite.JSON(), nullable=True),
        sa.Column("compare_config", sqlite.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.BIGINT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("prompt_debug_context", schema=None) as batch_op:
        batch_op.create_index(
            "ix_prompt_debug_context_prompt_id", ["prompt_id"], unique=False
        )

    # ### end Alembic commands ###
