apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  annotations:
    description: {{ .Values.secret.description }}
type: Opaque

data:
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
