"""feat: add_obs_name_column

Revision ID: 30acb51653ea
Revises: 4d8a6b1c2e9f
Create Date: 2026-03-02 11:52:58.848283

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from openjiuwen_studio.core.database.migration_utils import (
    table_exists,
    column_exists,
    index_exists,
)
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "30acb51653ea"
down_revision: Union[str, Sequence[str], None] = "072ac1293a02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema. 仅当表/列存在时执行 drop，避免历史库从未有过该结构时报错。"""
    if table_exists("user_message"):
        op.drop_table("user_message")
    if table_exists("scope_user_mapping"):
        op.drop_table("scope_user_mapping")
    if table_exists("knowledge_base") and column_exists("knowledge_base", "obs_name"):
        op.drop_column("knowledge_base", "obs_name")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "knowledge_base",
        sa.Column(
            "obs_name",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=1000),
            nullable=True,
            comment="OBS 存储路径前缀在存储桶中",
        ),
    )
    op.create_table(
        "scope_user_mapping",
        sa.Column(
            "user_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
            nullable=False,
        ),
        sa.Column(
            "scope_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", "scope_id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "user_message",
        sa.Column(
            "message_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
            nullable=False,
        ),
        sa.Column(
            "scope_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
            nullable=False,
        ),
        sa.Column(
            "content",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=4096),
            nullable=False,
        ),
        sa.Column(
            "session_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
            nullable=True,
        ),
        sa.Column(
            "role",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=32),
            nullable=True,
        ),
        sa.Column(
            "timestamp",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=32),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("message_id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
