#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
"""auto migration for latest ops schema changes

Revision ID: 7839d8387e0f
Revises: 13377a900fe2
Create Date: 2026-01-21 19:25:04.171976

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "7839d8387e0f"
down_revision: Union[str, None] = "13377a900fe2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_prompt_debug_context_prompt_id", table_name="prompt_debug_context"
    )
    op.drop_table("prompt_debug_context")
    op.drop_index("ix_prompt_debug_log_debug_id", table_name="prompt_debug_log")
    op.drop_index("ix_prompt_debug_log_prompt_id", table_name="prompt_debug_log")
    op.drop_table("prompt_debug_log")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_debug_log",
        sa.Column("id", mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("prompt_id", mysql.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("space_id", mysql.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("prompt_key", mysql.VARCHAR(length=128), nullable=False),
        sa.Column("version", mysql.VARCHAR(length=128), nullable=False),
        sa.Column("input_tokens", mysql.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("output_tokens", mysql.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("started_at", mysql.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("ended_at", mysql.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("cost_ms", mysql.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("status_code", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("debugged_by", mysql.VARCHAR(length=128), nullable=True),
        sa.Column("debug_id", mysql.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("debug_step", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("(now())"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(),
            server_default=sa.text("(now())"),
            nullable=True,
        ),
        sa.Column("deleted_at", mysql.BIGINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_prompt_debug_log_prompt_id", "prompt_debug_log", ["prompt_id"], unique=False
    )
    op.create_index(
        "ix_prompt_debug_log_debug_id", "prompt_debug_log", ["debug_id"], unique=False
    )
    op.create_table(
        "prompt_debug_context",
        sa.Column("id", mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("prompt_id", mysql.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("user_id", mysql.VARCHAR(length=128), nullable=False),
        sa.Column("mock_contexts", mysql.JSON(), nullable=True),
        sa.Column("mock_variables", mysql.JSON(), nullable=True),
        sa.Column("mock_tools", mysql.JSON(), nullable=True),
        sa.Column("debug_config", mysql.JSON(), nullable=True),
        sa.Column("compare_config", mysql.JSON(), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("(now())"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(),
            server_default=sa.text("(now())"),
            nullable=True,
        ),
        sa.Column("deleted_at", mysql.BIGINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_prompt_debug_context_prompt_id",
        "prompt_debug_context",
        ["prompt_id"],
        unique=False,
    )
    # ### end Alembic commands ###
